### ISSUE TITLE
Wrong group entry in .conf when adding "All domain users" ACL for file-share

### ISSUE THREAD

**Issue by mmram** [zentyal/zentyal#1813]
Version 5.1.1
When adding an ACL for a share for the predefined group "All domain users" the entry in /etc/samba/shares.conf is not @"Domain Users" but instead @"All domain users" or whatever the translated name is in the language selected in frontend (e.g. @"Alle Domänen-Benutzer" in german). This leads to a non-working ACL and non-accessible share because of the non-existing translated group.

Everything works fine if I change the .conf-entry to @"Domain Users" afterwards.

Frontend routines should write the non-translated group name to shares.conf here.

**Comment by doudz** [comment]
I just migrate to 5.1 this morning and I have the same problem.
For me it's not translated in french, it's @"All domain users" instead of @"Domain users"
Replacing entries in /etc/samba/shares.conf is a workaround but it's a bit annoying since changes are overwritten by zentyal when zentyal restart the share service

**Comment by doudz** [comment]
I create a PR to fix the problem
https://github.com/zentyal/zentyal/pull/1816

**Comment by Neustradamus** [comment]
@jacalvo soon?

**Comment by Neustradamus** [comment]
https://github.com/zentyal/zentyal/commit/9142b2fcc520f471680e0dcac23e60d8c7cb450f

**Comment by jacalvo** [comment]
thanks for the PR @doudz, but next time please use master as base branch

closing this as fix is commited
