### ISSUE TITLE
VM bridge mode doesn't work

### ISSUE THREAD

**Issue by igorbarney** [zentyal/zentyal#1868]
I just created a VM but it works only under NAT network option. I'm trying to set bridge mode up but the bridge to drop list just shows up none. What am I doing incorrectly or is this a bug?

**Comment by brunolorente** [comment]
Closing as duplicated https://github.com/zentyal/zentyal/issues/1853

**Comment by JOduMonT** [comment]
@brunolorente It is not really a duplicate because here, like me, the person is not able to create a bridge, while in [1853](https://github.com/zentyal/zentyal/issues/1853) the person succeed that 1st step.

> trying to set bridge mode up but the bridge to drop list just shows up none

Like @igorbarney I'm unable to create the bridge
![image](https://user-images.githubusercontent.com/5204724/132814807-0b7e9786-3e4e-4cf7-9331-0d56bab1b8c6.png)

After clicking CHANGE I have, with good reason, this message:
> The requested operation will cause one of the configured gateways or static routes to become unreachable. Please remove it first if you really want to make this change.

Of course, I could force the config as mentioned by @mrPsycho in 1853
https://wiki.libvirt.org/page/Networking#Debian.2FUbuntu_Bridging
But another complication is I'm using Zentyal 7 which is based on Ubuntu 20 which use netplan.io.

So; what is the plan ?
Does it mean I have to use Zentyal as a gateway for my VM
