### ISSUE TITLE
Bug 1925 is not resolved

### ISSUE THREAD

**Issue by sat-dish** [zentyal/zentyal#1926]
See closed bug 1925, The reported solution did not solve the issue.

**Comment by brunolorente** [comment]
Hi @sat-dish 

as the commit 68f2b755aca6c202f7fb384bff11f48e5d2f9ba7 says, it was a semantic versioning error in our repository, we have release a new version of dns package.

The error was fixed, closing the issue.

In order to tray to have all the issues well formed, at the next time, please, if you wish, try to use the bug issue template.

thank you
