### ISSUE TITLE
Zentyal 6.0.3 automatic updates

### ISSUE THREAD

**Issue by stefanmikroe** [zentyal/zentyal#1933]
Hi,

As an additional domain controller, Zentyal 6, I don't have a feature to turn off automatic updates(see picture below).
![zentyal automatic updates](https://user-images.githubusercontent.com/45256129/71443220-0bd6bc80-270a-11ea-8880-7dc132720b4e.jpg)

How can I turn it off?

**Comment by mrPsycho** [comment]
to turn off updates you can comment all repos in /etc/apt/sources.list and /etc/apt/sources.list.d/*
to turn it on uncomment.


ps. forget about zentyal. developer don't care anything about free version. 
and i don't believe they do something on paid version.

**Comment by stefanmikroe** [comment]
I have a commercial version of two servers. First one has that option to turn off, second one doesn't.

**Comment by brunolorente** [comment]
Hi @stefanmikroe,

This is an expected behaviour. In community versions you can disable the automatic updates through the WebAdmin, however, in the Commercial versions you must use the configuration file '/etc/zentyal/zentyal.conf' (remember to restart the webadmin module after make any change).

About the suggestion of @mrPsycho , we don't recommend you to comment out a repository as a way to change the normal behaviour of the system. You have to use the ways offered by Zentyal (stubs, conf files, and hooks).

Also, note @mrPsycho that you have the forum available for questions or configuration issues related to Zentyal, our GitHub channel should be used for reporting bugs or enhancements.

Thanks!

**Comment by stefanmikroe** [comment]
> restart the webadmin module

Thank you! It works...
