### ISSUE TITLE
Zentyal 6[.1] installation issue 1

### ISSUE THREAD

**Issue by wintelkiller** [zentyal/zentyal#1935]
During Installation of Zentyal 6[.1] the system tries to load files from the repositories on the server. 
This will be quitted with an errors.
After manual re-establishing of the ipv4-setting of the interface "eth0", the installation can be continued using "sudo apt update --fix-missing".

**Comment by djoven89** [comment]
Hi @wintelkiller,

Please, use the available template to create the issue, otherwise, we will close the issue.

As an additional information, until you reboot the Zentyal server after the installation have been complete, you will have an entry in the '**sources.list'** file which points to a temporal repository located in the server.

Happy New Year!

**Comment by djoven89** [comment]
Closing the issue because you didn't follow the template.
