### ISSUE TITLE
Bug in add a new Object

### ISSUE THREAD

**Issue by gustisak** [zentyal/zentyal#1950]
**Describe the bug**

when trying to add an object on the network such an error always happens

**To Reproduce**
1. Go to NETWORK - NETWORK - Insert the name of object , ip and MAC address
2. Click on CHANGE
4. See error "Sinto muito, você encontrou um bug no Zentyal. Cheque por detalhes no arquivo /var/log/zentyal/zentyal.log e leve um minuto para submeter um relato de bug para que possamos corrigí-lo logo que for possível." The language is Portuguese

**Expected behavior**

I need to change and add objects on the network

**Screenshots**
![zentyal](https://user-images.githubusercontent.com/61876082/76090425-51c9bf80-5f9a-11ea-83a9-2f19b54890fe.PNG)

**Zentyal OS (please complete the following information):**
 - Version: [3.3]
 - Version of the module which has the bug [Zentyal Network]
 - Modules installed [REDE, FIREWALL, DNS, ANTIVÍRUS, DHCP,BACKUP, EVENTOS, IDS, LOGS, MONITORAÇÃO , NTP, VPN, USUÁRIOS E COMPUTADORES, SERVIDOR WEB, MONITOR DE BANDA, FTP, FILE SHARING, ÁREA DE USUÁRIO, IMPRESSORAS]

**Other OS (please complete the following information):**
 - OS: [ Windows 10]
 - Version: [ build 18363]

**Additional context**

**Comment by brunolorente** [comment]
Hi @gustisak ,

We tried to reproduce this bug in Zentyal 6 but we couldn't. It seems that your old Zentyal 3.3 has some issues, but unfortunately, the support for that version expired long time ago. 

We highly recommend you to use a supported version in order to have updates from Ubuntu repositories and the new features of Zentyal.

Regards!
