### ISSUE TITLE
VPN disconnect after saving changes

### ISSUE THREAD

**Issue by ethanjosephscott** [zentyal/zentyal#1955]
Hey Gang,
With the world as it is we have more remote workers than ever.  Whenever the zentyal webGUI saves changes, it restarts the VPN server and all of the clients disconnect in the process.  Trust me utilizing the built-in VPN and making changes at the same time to the Zentyal server can be a multiple minute process after connections reestablish.  With the way things are now I will have to wait until the end of the work day to do any changes regarding DNS, DHCP, etc... 

Can we change things up to make it so where the VPN doesn't restart after applying configuration changes?

**Comment by djoven89** [comment]
Hi @ethanjosephscott ,

Depending of the changes that you do in the Zentyal Admin Interface it affects to more or less modules, and when a module is affected, Zentyal restarts it in order to apply the configuration that was set through the GUI. 

So, we're sorry but there is nothing we can do to change this behaviour.

Best regards, Daniel Joven.
