### ISSUE TITLE
zentyal-PDC integrated keycloak

### ISSUE THREAD

**Issue by dudumao520** [zentyal/zentyal#1960]
Hello everyone.
I have deployed zentyal-PDC domain controller, I want to integrate with keycloak，but no success

**Comment by brunolorente** [comment]
Hi @dudumao520 ,

I'm sorry but this repo is used to report bugs or request a new feature, and also, the provided template must be used.

In your case, you need to create a new thread in the official Zentyal forum and provide all the details you are able to provide in order to get help, for example, the version of Zentyal, the steps and/or errors you did, an image of the keycloak configuration, etc.

Best regards.
