### ISSUE TITLE
ERROR CONSOLE

### ISSUE THREAD

**Issue by alanmarconcin** [zentyal/zentyal#1990]
**Describe the bug**
Erro ao acessar a console

![image](https://user-images.githubusercontent.com/33225024/91332493-a65c3380-e7a2-11ea-8d6f-1a93e838add9.png)

**Comment by djoven89** [comment]
Hi @alanmarconcin ,

That is a normal message, you get it when you don't do any action in the windows after a while (inactive session).

Also, please, for future reports, remember to use the template to create a bug/enhancement.

Best regards, Daniel Joven.

**Comment by jmglara83** [comment]
Hello, but the same thing happens to me, but it is not due to inactivity, since I installed it for the 5 time to Zentyal it is always the same, I get tired of being bothered by this error, because apparently several people are unaware of it.
Use the option to use a KVM manager.
Everyone asks where they can, so someone with good knowledge helps you. Guide does not scold.

**Comment by Neustradamus** [comment]
@brunolorente, @djoven89: Can you look the last comment?
