### ISSUE TITLE
Add option for wildcard hostname in DNS

### ISSUE THREAD

**Issue by dirkey** [zentyal/zentyal#2028]
It's currently not possible to add a hostname with wildcard support. If i add dev as a hostname, i like to resolv all *.dev to this address. Either adding a checkbox or allowing to enter *.dev in the hostname field will solve this problem.

**Comment by djoven89** [comment]
Hi @dirkey ,

Thank you for your feedback, however, I'm sorry to inform you that I have to close the issue because you didn't use the template. Please, open a new issue using the correct format and we will analyze it. Also, remember that you can contribute with the project by developing the suggested enhancement and creating a Pull Request.

Best regards, Daniel Joven.

**Comment by Neustradamus** [comment]
@dirkey: Can you create a new issue?

**Comment by dirkey** [comment]
> @dirkey: Can you create a new issue?

No, I switch to NethServer. Which supports this feature and is much more community driven.

**Comment by loxK** [comment]
I've done it : https://github.com/zentyal/zentyal/issues/2182
