### ISSUE TITLE
Fresh install and losing access to the internet after complete

### ISSUE THREAD

**Issue by ranrinc** [zentyal/zentyal#2110]
**Describe the bug**
fresh install zentyal and after web installation, it will hang upon completion. Furthermore from this point on Zentyal will not have access to the internet. Ping google will come back with "Temporary failure in name resolution"

**To Reproduce**
1. Clean Install <- on Proxmox VM
2. go to the IP:8443 
3. run the installation
4. I put my IP, gateway, DNS -> my gateway + 8.8.8.8
5. the screen stop upon webmin installation
6. restart the browser IP:8443
7. Unable to update or ping google

**Expected behavior**

**Screenshots**

**Zentyal OS (please complete the following information):**
 - Version: 7.0

Does anyone have solutions?

**Comment by djoven89** [comment]
Hi @ranrinc ,

Unfortunately, this issue is very similar to [this](https://github.com/zentyal/zentyal/issues/2100) another bug.

Did you check if the network configuration you set in the wizard was applied? The network module is enabled? Did you check the network using the CLI (`ip` command mainly)? Finally, did you try to restart or disable and enable the network module?

Best regards, Daniel Joven.

**Comment by ranrinc** [comment]
Hi @djoven89,

I double check before zentyal installation which is ubuntu 20.04 did have internet connections. Again it's a clean install, the ubuntu itself is freshly installed. Upon running the script everything still working. However, after the installation process in the browser which shows all the installed modules <- I think all are installed. And after inputting all the data the problem arise after it stuck on webmin update. 

Rebooting or doing anything else did not solve the issue. Furthermore trying connecting using admin from Win11 ended up with the wrong username/password. So far did not find any solutions. P.S. one of my friend who tries to install zentyal also having  a similar issue without any resolutions

**Comment by ranrinc** [comment]
Any update on this issue?

**Comment by djoven89** [comment]
Hi @ranrinc ,

Let's try another approach. Please, do the following:

1. Install a Ubuntu Server 20.04 LTS as a virtual machine on Proxmox.
2. Make sure you have internet access.

	```
	ping google.es
	```

3. Update the Ubuntu server packages:

	```
	sudo apt update
	sudo apt dist-upgrade -y
	```

4. Install Zentyal using [this](https://doc.zentyal.org/en/installation.html#installation-on-top-of-ubuntu-20-04-lts-server-or-desktop) script.

5. In the wizard configuration, only install the firewall module.
6. Configure the network configuration (internal).
7. When you save changes, it will get stuck because of [this](https://github.com/zentyal/zentyal/issues/2100) bug.
8. In the URL, remove from the port to the end, for example:

	```
	## This is the URL I got when the saving changes are stuck
	https://192.168.1.152:8443/SaveChanges?noPopup=1&save=1&firstTime=1

	## This is the 'new' URL after the change
	https://192.168.1.152:8443
	```

At this point, the three modules must be enabled, and your Zentyal server should have the network configuration applied.

```
sudo ip -4 a
sudo ip route s
sudo ping google.es
```

If it still does not work, analyze the current network status with the above commands, analyze the following log files and finally, disable the network module, save changes, and enable it again.

* /var/log/zentyal/zentyal.log
* /var/log/syslog

**NOTE:** Remember that Windows 11 cannot be joined to the Zentyal domain controller due to a Samba bug. In [this](https://doc.zentyal.org/en/workaround-windows11.html) link you have the available workarounds you have.

Hope it helps you.

**Comment by ranrinc** [comment]
@djoven89,

Thank you for all the help and finally have zentyal working.

For those who are experiencing problems this is actually the solution:

The server on Proxmox + Ubuntu 20.04 freshly installed
Once this is installed you will surely get Local IP + Internet
Be sure to update
`sudo apt update && sudo apt dist-upgrade -y && sudo apt autoremove`

Install Zentyal as is Domain Controller etc <- this will install until it asks for setting IP
Setup per usual and DNS to 8.8.8.8 + 1.1.1.1 or whatever you want

In the end, this will stop at updating webmin <- @djoven89 instructions point 7.
After this is complete 100% sure you will lose Internet connections.
To fix this go to the DNS menu and make sure you add your forwarders 8.8.8.8 + 1.1.1.1 and save.
This will turn back on your internet.

As for Windows 11 again you can follow @djoven89 Note regarding samba bugs.

P.S. Webmin bugs are really annoying at this point in time, but it did not stop zentyal.

I hope this will help. Again my special thanks to @djoven89 for all his help.

**Comment by djoven89** [comment]
Glad to help @ranrinc .
