### ISSUE TITLE
Users and Computers > getting this error. Sorry, an unexpected error has occurred

### ISSUE THREAD

**Issue by aslamraza09** [zentyal/zentyal#2111]
Users and Computers > getting below error.

Sorry, an unexpected error has occurred

Can't call method "children" on an undefined value at /usr/share/perl5/EBox/Samba/Model/Manage.pm line 77. Stack: [/usr/share/perl5/EBox/Samba/Model/Manage.pm:77] [/usr/share/perl5/EBox/Model/TreeView.pm:484] [/usr/share/perl5/EBox/Model/TreeView.pm:495] [/usr/share/perl5/EBox/Model/TreeView.pm:495] [/usr/share/perl5/EBox/Model/TreeView.pm:495] [/usr/share/perl5/EBox/Model/TreeView.pm:462] [/usr/share/zentyal/templates/ajax/treeView.mas:81] at /usr/share/perl5/EBox/CGI/Base.pm line 364

<img width="1676" alt="Screenshot 2022-11-18 at 9 08 22 PM" src="https://user-images.githubusercontent.com/78476609/202742797-0d4be6ee-d448-4db7-8447-6d502f833734.png">

**Comment by djoven89** [comment]
Hi @aslamraza09 ,

I'm sorry but I have to close this issue, you did not use the issue template and also, you did not provide us the necessary information to determine if it is a bug or not (what version of Zentyal are you using, what actions did you do, if there were previous changes, the content of the log file `/var/log/zentyal/zentyal.log`, etc)

I highly recommend you use the [forum](https://forum.zentyal.org/) for this particular case because it does not seems a bug but a system issue.

Best regards, Daniel Joven.
