### ISSUE TITLE
Windows 11 22H2 not allow login 

### ISSUE THREAD

**Issue by himala76** [zentyal/zentyal#2113]
When connecting the new windows 11 version 22H2 to Zentyal domain it shows authentication failed. To connect to the domain you have to edit the local security policy  local policies security options network security configure encryption types allow or Kerberos check only DES_CBC__CRC and DES_CBC_MD5>

Then your windows client will connect. But after that, you can't get the group policy working.

**Comment by djoven89** [comment]
Hi @himala76 ,

This bug was managed in [this](https://github.com/zentyal/zentyal/issues/2106) closed issue. The available workarounds to fix this issue are available [here](https://doc.zentyal.org/en/workaround-windows11.html).

**NOTE:** Next time you need to create an issue, please, use the available template.

Best regards, Daniel Joven.
