### ISSUE TITLE
Webmin configuration gets stuck at 100

### ISSUE THREAD

**Issue by herwinux** [zentyal/zentyal#2114]
After installing Zentyal 7.0 community vfersion, the configuration gets stuck at 100% and does not pass from there
![imagen](https://user-images.githubusercontent.com/55635553/205686011-f8486735-f14b-4ab9-ba6b-faaded60948d.png)

![imagen](https://user-images.githubusercontent.com/55635553/205695146-6eb69e64-7132-41b1-8fdf-ec2c0e06c2da.png)

It always stays 100% and does not pass from there.

**Comment by djoven89** [comment]
Hi @herwinux ,

This bug is reported in [this](https://github.com/zentyal/zentyal/issues/2100) issue.

**NOTE-1:** Just rewrite the URL until 'https://localhost:8443' when you get this behavour.
**NOTE-2:** Next time you create an issue or enhancement, please, use the available template.

Best regards, Daniel Joven.

**Comment by rubenszolt** [comment]
Confirm the problem, fresh install on 3 servers, cannot finalizing the install, it stuck on last step when **module webadmin save**, it must manually access https://IP:8443.
Core version 7.0.5 - no updates.
