### ISSUE TITLE
Backup Configuration Fails

### ISSUE THREAD

**Issue by rthomasii** [zentyal/zentyal#2119]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11380714/221238207-34352e5f-0d75-4bdc-a6d8-df87212aed23.png)

**To Reproduce**
1. Go to 'backup Configuration' > New Backup

**Expected behavior**
Backup should complete

**Screenshots**
Attached

**Zentyal OS (please complete the following information):**
 - Version: 7.0.5
 - ??
 - Modules installed [all except HTTP proxy]

**Other OS (please complete the following information):**
 - OS: Linux Ubuntu 
 - Version: [Linux server1 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]

**Additional context**

**Comment by djoven89** [comment]
Hi @rthomasii ,

That error is caused by an update from Mysql as you can read [here](https://github.com/mysql/mysql-server/commit/022e73ba6976b984658a1c2652178cd4b81aec28#commitcomment-98151933).

The required actions to be able to run mysqldump in the Sogo database are:

1. Log in as `root` user in the database:

	```sh
	mysql -u root -p$(sudo cat /var/lib/zentyal/conf/zentyal-mysql.passwd)
	```

2. Ensure that the user 'sogo'@'127.0.0.1' exists and it has the same permissions as follows:

	```sh
	select `User`,`HOST`, `Process_priv`,`Reload_priv` from mysql.user where user='sogo';

	+------+-----------+--------------+-------------+
	| User | HOST      | Process_priv | Reload_priv |
	+------+-----------+--------------+-------------+
	| sogo | 127.0.0.1 | N            | N           |
	+------+-----------+--------------+-------------+
	```

3. If you get the same output, grant it the necessary permissions it needs to be able to use `mysqldump`:

	```sh
	GRANT RELOAD,PROCESS ON *.* TO 'sogo'@'127.0.0.1';
	FLUSH PRIVILEGES;
	```

4. Confirm that the user has the correct permissions now:

	```sh
	select `User`,`HOST`, `Process_priv`,`Reload_priv` from mysql.user where user='sogo';

	+------+-----------+--------------+-------------+
	| User | HOST      | Process_priv | Reload_priv |
	+------+-----------+--------------+-------------+
	| sogo | 127.0.0.1 | Y            | Y           |
	+------+-----------+--------------+-------------+
	```

5. Finally, try to generate a new configuration backup.

We have planned to release a package that runs those commands, but in the meantime, you can apply the above fix.

Best regards, Daniel Joven.
