### ISSUE TITLE
Zentyal -Users and computers -missing element

### ISSUE THREAD

**Issue by siz0pt** [zentyal/zentyal#2126]
Hi,
I'm having this issue, i cant open Users and Computers managment and also DNS page, its giving me missing element.
The problem is with RSAT i cant access to the domain, now i need to create a user for the company and im stuck.
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/102173573/229750668-4e78c245-f7aa-48ac-a176-4a944728d590.png)

 - Zentyal Commercial Edition version: 7

**Comment by djoven89** [comment]
Hi @siz0pt ,

This bug was reported [here] and solved a few weeks ago. In your case, probably, you are still getting this bug because you do not have access to Zentyal commercial repository.

Last year the repository key expired and if you did not import the new one, you do not have access to the repository so you do not have access to the package that fixes the bug. In [this] message from the forum, you have the required actions to fix the issue.

[here]: https://github.com/zentyal/zentyal/issues/2121
[this]: https://forum.zentyal.org/index.php/topic,35100.msg115467.html#msg115467

Best regards, Daniel Joven.

**Comment by siz0pt** [comment]
> Hi @siz0pt ,
> 
> This bug was reported [here] and solved a few weeks ago. In your case, probably, you are still getting this bug because you do not have access to Zentyal commercial repository.
> 
> Last year the repository key expired and if you did not import the new one, you do not have access to the repository so you do not have access to the package that fixes the bug. In [this] message from the forum, you have the required actions to fix the issue.
> 
> [here]: https://github.com/zentyal/zentyal/issues/2121
> [this]: https://forum.zentyal.org/index.php/topic,35100.msg115467.html#msg115467
> 
> Best regards, Daniel Joven.


Thank you mate, 

That solved the issue with the users, but DNS don't. I still can't access the domain or even login the new user.

**Comment by siz0pt** [comment]
The service now it's running, something changed to better . But still saying element not found at DNS config page
