### ISSUE TITLE
Zentyal 7.1 spotted - can we have some change log please

### ISSUE THREAD

**Issue by dzidek23** [zentyal/zentyal#2133]
As mentioned by "half_life" forum user [here](https://forum.zentyal.org/index.php/topic,35594.msg115596.html#msg115596) a new version of Zentyal has show up. Any chance for a change log?

Looks identical to 7.0.x but runs quicker (in test, with no load)
Errors during final steps of installation where the GUI wizard hangs on configuring SAMBA.

For interested, link to the [download](https://download02.public.zentyal.com/)

**Comment by djoven89** [comment]
Hi @dzidek23 

Can you please open an issue with the errors you get during the installation of Zentyal 7.1? We would like to have all the feedback possible in order to improve the new ISO installer, which is located in [this](https://github.com/zentyal/iso-generator) repository.

Regarding the change log, it will be published in this [link](https://wiki.zentyal.org/wiki/Announcements_and_Changelogs) as soon as it is available. In the meantime, you can get an idea by checking the commits in branch 7.1 [here](https://github.com/zentyal/zentyal/commits/7.1) you have the link.

**Comment by meiser79** [comment]
Zentyal 7.1 is available now.

**Comment by djoven89** [comment]
Hi @dzidek23 ,

[Here](https://wiki.zentyal.org/wiki/Announcements_and_Changelogs) you have the link with the announcement and the changelog you were looking for.
