### ISSUE TITLE
ADD AI

### ISSUE THREAD

**Issue by Sepp1911** [zentyal/zentyal#2141]
JUST TO MAKE SURE you don't miss it..

AI IS THE FUTURE

LETS JOIN THE BAND WAGON

**Comment by djoven89** [comment]
Hi @Sepp1911,

We are sorry but we are going to close this issue as invalid because of the following reasons:

1. Everything is in uppercase.
2. You did not propose a solution to implement.

You can create a new enhancement issue but ensure the text is correctly formatted, provide solutions and explain why you believe they should be implemented.
